version: 2

builds:
  - main: .
    binary: claw-migrate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{- if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{- if and (eq .Os "darwin") (eq .Arch "arm64") }}apple-silicon{{- else if and (eq .Os "darwin") (eq .Arch "amd64") }}intel{{- else if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{- end }}'
    format_overrides:
      - goos: darwin
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: arunbluez
    name: claw-migrate